version: 2
jobs:
  build:
    docker:
      - image: meshredded/circleci-vsce:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: npm install
          command: npm install


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: npm install
          command: npm install

      - run:
          name: npm run vscode:prepublish
          command: npm run vscode:prepublish
      - run:
          name: vsce package
          command: vsce package
      - run:
          name: vsce publish
          command: vsce publish -p ${azure_key}